### ISSUE TITLE
Error "Ambiguous cop name `RSpec/Rails/HttpStatus`" with latest rubocop-rspec and rubocop-rspec_rails

### ISSUE THREAD

**Issue by mjankowski** [rubocop/rubocop-rspec_rails#18]
Following up on conversation here - https://github.com/rubocop/rubocop-rspec_rails/issues/9#issuecomment-2029695155

Here's a minimal reproduction case. There are two files: `Gemfile`, and a minimal `.rubocop.yml`.

Gemfile:

```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false
```

Configuration in .rubocop.yml:

```
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/Rails/HttpStatus:
  EnforcedStyle: numeric
```

With this setup, when I run `bundle exec rubocop`, I get error output:

> Error: Ambiguous cop name `RSpec/Rails/HttpStatus` used in /Users/mjankowski/repos/tester/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpecRails/HttpStatus?

If I comment out the `require` line for `rubocop-rspec` in the rubocop.yml (so only rubocop-rails is req'd), the ambiguous error goes away and I get the deprecation warning:

> .rubocop.yml: RSpec/Rails/HttpStatus has the wrong namespace - replace it with Rails/HttpStatus

If I restore that line and comment out the `rubocop-rails` line (so only rubocop-rspec is req'd), I get this warning:

> .rubocop.yml: RSpec/Rails/HttpStatus has the wrong namespace - replace it with RSpecRails/HttpStatus

If this matters, I'm running: ruby 3.3.0, rubygems 3.5.7, bundler 2.5.7. Output from `bundle list`:

```
Gems included by the bundle:
  * activesupport (7.1.3.2)
  * ast (2.4.2)
  * base64 (0.2.0)
  * bigdecimal (3.1.7)
  * concurrent-ruby (1.2.3)
  * connection_pool (2.4.1)
  * drb (2.2.1)
  * i18n (1.14.4)
  * json (2.7.1)
  * language_server-protocol (3.17.0.3)
  * minitest (5.22.3)
  * mutex_m (0.2.0)
  * parallel (1.24.0)
  * parser (3.3.0.5)
  * racc (1.7.3)
  * rack (3.0.10)
  * rainbow (3.1.1)
  * regexp_parser (2.9.0)
  * rexml (3.2.6)
  * rubocop (1.62.1)
  * rubocop-ast (1.31.2)
  * rubocop-capybara (2.20.0)
  * rubocop-factory_bot (2.25.1)
  * rubocop-rails (2.24.1)
  * rubocop-rspec (2.28.0)
  * rubocop-rspec_rails (2.28.2)
  * ruby-progressbar (1.13.0)
  * tzinfo (2.0.6)
  * unicode-display_width (2.5.0)
Use `bundle info` to print more detailed information about a gem
```

**Comment by mjankowski** [comment]
Maybe more useful debugging ... I add some other obsoleted cops to the config, and removed the httpstatus one. I see output like:

> .rubocop.yml: RSpec/Rails/InferredSpecType has the wrong namespace - replace it with RSpecRails/InferredSpecType

and:

> Error: The `Lint/MultipleCompare` cop has been renamed to `Lint/MultipleComparison`.

(Note how the MultiCompare is the obsoletion error, and the `InferredSpecType` is a standard namespace warning)

When I add some debug output to the ConfigObsoletion class, it does seem to have the appropriate values in the `files` class attr, but it doesn't seem to be fully applying/merging those rules. I'm not familiar enough with rubocop internals to know what order these things are supposed to be applied in.

**Comment by pirj** [comment]
@dvandersluis do you think you know why this can happen?

**Comment by Vagab** [comment]
wanted to chime in here, I'm rubocop with solargraph inside neovim, and I have this in my `.rubocop.yml`:
```ruby
RSpecRails/HttpStatus:
  EnforcedStyle: numeric
```
if I open up lsp logs I can see the following error:
```
Error processing request: [RuboCop::Cop::AmbiguousCopName] Ambiguous cop name `RSpecRails/HttpStatus` used in <some_path>/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpec/Rails/HttpStatus?
```

**Comment by genericsteele** [comment]
We're also still running into this issue. It's blocked a number of our internal gems in CI. We've had to lock `rubocop-rspec` below `v.2.28.0` to avoid it.

**Comment by pirj** [comment]
@rubocop/rubocop-rspec do we know what us causing this? Should this be fixed somewhere in RuboCop’s ConfigLoader? What is the course of action? Do we admit our failure with this and recommend to adjust project configs with a minor version update?

**Comment by ydah** [comment]
I have found a repository to reproduce and will investigate. Sorry for the delay.

**Comment by mjankowski** [comment]
After update to rubocop-rspec_rails 2.28.3 I now just see the expected wrong namespace warnings, but no longer get the ambiguous cop warning. Looks good, thanks!

**Comment by ydah** [comment]
@mjankowski I really appreciate you reporting this issue! Thank you!
