### ISSUE TITLE
`rubocop-rsepc_rails` not compatible with `rubocop-rspec` v3

### ISSUE THREAD

**Issue by tim-s-ccs** [rubocop/rubocop-rspec_rails#41]
I realise that v3 of `rubocop-rsepc` has only just been released but I thought I'd raise this anyway.

`rubocop-rsepc_rails` requires `'rubocop/rspec/language/node_pattern'` which can be seen here: https://github.com/rubocop/rubocop-rspec_rails/blob/master/lib/rubocop-rspec_rails.rb#L8

However, v3 `rubocop-rsepc` has removed this file (not sure if moved, deleted or changed) and so `rubocop` crashes when requiring `rubocop-rsepc_rails`

---
Note the below commnad actually crashes but I am able to work out what it would output
```
rubocop -V
```
Output:
```
1.64.1 (using Parser 3.3.2.0, rubocop-ast 1.31.3, running on ruby 3.3.1) [x86_64-darwin22]
  - rubocop-capybara 2.20.0
  - rubocop-factory_bot 2.25.1
  - rubocop-rails 2.25.0
  - rubocop-rspec 3.0.0
  - rubocop-rspec_rails 2.28.3
```

**Comment by tim-s-ccs** [comment]
And I forgot to check the PRs as I can see this is being looked at in https://github.com/rubocop/rubocop-rspec_rails/pull/30

I'll leave this issue open for now but, obviously, feel free to close it if you feel that is appropriate,

**Comment by mjankowski** [comment]
Thanks for quick fix+release on this. Updated and error resolved.
