### ISSUE TITLE
Could you add a repository homepage to GitHub?

### ISSUE THREAD

**Issue by valscion** [rubocop/rubocop-rspec_rails#44]
Hi!

Would you be up for adding a doc link to this repository so that it's visible in the GitHub sidebar here?

> <img width="492" alt="image" src="https://github.com/rubocop/rubocop-rspec_rails/assets/482561/9bd6b71b-a2d4-49c5-b2b4-08cbbb00b775">

I checked the other gems for reference and this one was the only one where the website was not yet configured:

> <img width="492" alt="image" src="https://github.com/rubocop/rubocop-rspec_rails/assets/482561/0889cb5d-9eda-46bb-87d4-cb4337475744">
> 
> <img width="492" alt="image" src="https://github.com/rubocop/rubocop-rspec_rails/assets/482561/0c6d2f48-4a82-4703-be01-8a1e2f78334b">
> 
> <img width="492" alt="image" src="https://github.com/rubocop/rubocop-rspec_rails/assets/482561/14d6218f-d967-4a15-9db2-643412a60784">
> 

It would make it just a tad bit faster to jump to docs given now that you have released `rubocop-rspec` v3 (and congrats for releasing! 👏)

**Comment by pirj** [comment]
That would be great, a PR is welcome

**Comment by valscion** [comment]
Huh, I thought it was in some settings page 😅 I'll look into how that one works if a PR is possible for that.

**Comment by pirj** [comment]
You're right. I was thinking it's docs, not GitHub.
@bquorning can you please change the repo desciption to include https://docs.rubocop.org/rubocop-rspec_rails/ and tags?

**Comment by bquorning** [comment]
Thank you for the suggestion. I have added the link and some tags.
